In [41]:
import librosa
import numpy as np
import matplotlib.pyplot as plt
import scipy
import librosa.display
import IPython.display as ipd

In [2]:
filename = librosa.util.example_audio_file()

In [3]:
x,sr = librosa.load('Yaman.wav', sr = None, offset = 15, duration = 5)

In [4]:
x

array([-0.31080627, -0.32115173, -0.32835388, ..., -0.11395264,
       -0.12515259, -0.13719177], dtype=float32)

In [18]:
sr

44100

In [5]:

filename = 'Yaman.wav'
x, sr = librosa.load(filename)
# trim silent edges
whale_song, _ = librosa.effects.trim(x)

In [6]:
trim, _ = librosa.effects.trim(x)

In [49]:
frequencies = np.fft.fft(trim)

In [44]:
frequencies

array([ 44.37164146 +0.j        ,  10.02549233+78.81548931j,
       -23.04944524+21.97575459j, ...,   3.09601891+76.46251063j,
       -23.04944524-21.97575459j,  10.02549233-78.81548931j])

In [47]:
abs(frequencies[0] * sr)

978394.6941070362

In [27]:
data_size = 10439680

data = trim

w = np.fft.fft(data)
freqs = np.fft.fftfreq(len(w))
print(freqs.min(), freqs.max())
# (-0.5, 0.499975)



-0.5 0.4999999042116234


In [29]:
# Find the peak in the coefficients
frate = sr
idx = np.argmax(np.abs(w))
freq = freqs[idx]
freq_in_hertz = abs(freq * frate)
print(freq_in_hertz)

293.16627042208194


In [38]:
frequencies = []
for i in list(freqs):
    frequencies.append(abs(sr*i))

In [39]:
frequencies

[0.0,
 0.0021121337052476706,
 0.004224267410495341,
 0.006336401115743012,
 0.008448534820990682,
 0.010560668526238352,
 0.012672802231486023,
 0.014784935936733693,
 0.016897069641981365,
 0.019009203347229036,
 0.021121337052476704,
 0.023233470757724375,
 0.025345604462972047,
 0.02745773816821972,
 0.029569871873467386,
 0.03168200557871506,
 0.03379413928396273,
 0.0359062729892104,
 0.03801840669445807,
 0.04013054039970574,
 0.04224267410495341,
 0.04435480781020109,
 0.04646694151544875,
 0.04857907522069642,
 0.050691208925944094,
 0.05280334263119177,
 0.05491547633643944,
 0.0570276100416871,
 0.05913974374693477,
 0.061251877452182454,
 0.06336401115743012,
 0.06547614486267778,
 0.06758827856792546,
 0.06970041227317314,
 0.0718125459784208,
 0.07392467968366846,
 0.07603681338891614,
 0.07814894709416381,
 0.08026108079941148,
 0.08237321450465915,
 0.08448534820990682,
 0.0865974819151545,
 0.08870961562040218,
 0.09082174932564983,
 0.0929338830308975,
 0.095046016736

In [8]:
trim

array([-0.00116679, -0.00098743, -0.000893  , ...,  0.00136606,
        0.00124926,  0.00101575], dtype=float32)

In [83]:
filename = 'abcd.ogg'
x, sr = librosa.load(filename)
# trim silent edges
trim, _ = librosa.effects.trim(x)

In [53]:
X = librosa.stft(x)
S = librosa.amplitude_to_db(abs(X))

In [84]:
pitches, magnitudes = librosa.piptrack(x, sr)



In [86]:
pitches

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)